version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules   # evita conflito dos node_modules do host com os do container
    command: npm run dev
    environment:
      - WATCHPACK_POLLING=true   # ajuda o Next a detectar mudanças dentro do Docker

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
