# app/schemas/plan.py

from pydantic import BaseModel
from typing import List, Optional


class PlanStep(BaseModel):
    """Represents a single step generated by the Planner."""
    id: int
    description: str
    tool: Optional[str] = None
    input: Optional[dict] = None


class PlanResponse(BaseModel):
    """Response model returned by the Planner."""
    task: str
    steps: List[PlanStep]