version: '3.8'

services:
  personal-agent:
    build: .
    container_name: personal-agent
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./credentials:/app/credentials
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    env_file:
      - .env
