version: '3.8'

services:
  summarizer:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - ./db:/app/db
      - ./db/chroma_persist:/app/db/chroma_persist
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - USE_OPENAI=${USE_OPENAI:-true}
    restart: unless-stopped
